---
- name: Configure EC2 Web Server
  hosts: webserver
  become: yes
  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: latest

    - name: Start and Enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy Custom Web Page
      copy:
        content: "<h1>Welcome to Paul Graves's Terraform & Ansible EC2 Server :)</h1>"
        dest: /usr/share/nginx/html/index.html
